version: '3.8'

services:
  mcp-server:
    build: .
    container_name: mcp-http-server
    ports:
      - "3000:3000"
    environment:
      - MCP_SERVER_NAME=MCP HTTP Template Server
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3000
      - MCP_LOG_LEVEL=INFO
      - MCP_ENABLE_TOOLS=true
      - MCP_ENABLE_RESOURCES=true
      - MCP_ENABLE_PROMPTS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/mcp/", "-H", "Accept: application/json, text/event-stream"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security options
    security_opt:
      - no-new-privileges:true
    # Read-only root filesystem (optional, uncomment if needed)
    # read_only: true
    # tmpfs:
    #   - /tmp:noexec,nosuid,size=100m
    
  # Development version with volume mount
  mcp-server-dev:
    build: .
    container_name: mcp-http-server-dev
    ports:
      - "3001:3000"
    environment:
      - MCP_SERVER_NAME=MCP HTTP Template Server (Dev)
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3000
      - MCP_LOG_LEVEL=DEBUG
      - MCP_ENABLE_TOOLS=true
      - MCP_ENABLE_RESOURCES=true
      - MCP_ENABLE_PROMPTS=true
    volumes:
      - ./mcp_server:/app/mcp_server:ro
    restart: unless-stopped
    profiles:
      - dev
